# Generated by Django 3.2.5 on 2021-07-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=12)),
                ('price', models.PositiveSmallIntegerField()),
                ('dates', models.DateField()),
            ],
        ),
    ]
