# Generated by Django 3.2.4 on 2021-08-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_auto_20210808_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendars',
            name='event_attendees',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
