# Generated by Django 3.2.4 on 2021-08-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0003_alter_calendars_event_attendees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendars',
            name='event_duration',
        ),
        migrations.AddField(
            model_name='calendars',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendars',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendars',
            name='event_agenda',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='calendars',
            name='event_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
