# Generated by Django 3.2.4 on 2021-09-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0006_auto_20210902_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendars',
            name='event_id',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
