# Generated by Django 3.2.7 on 2021-09-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0008_auto_20210903_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendars',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendars',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
