# Generated by Django 3.2.4 on 2021-08-20 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_auto_20210808_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='image',
        ),
    ]
