# Generated by Django 3.2.5 on 2021-07-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=12)),
                ('unit_id', models.CharField(max_length=14)),
                ('stack', models.CharField(max_length=12)),
                ('marketability', models.CharField(max_length=9)),
            ],
        ),
    ]
