# Generated by Django 3.2.4 on 2021-08-13 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210813_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='health_records',
        ),
    ]
