# Generated by Django 3.2.4 on 2021-08-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_student_health_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='health_records',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
